# Build Multitarget Application
name: Build MTA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: Install MTA Build Tool (NPM)
      run: npm install -g mbt
    # Do not generate package-lock.json
    # See https://blogs.sap.com/2020/07/07/escaping-eintegrity-hell/
    #- name: Disable package-lock.json
    #  run: npm config set package-lock false
    - name: Build MTA
      run: mbt build -p cf
    #- name: Upload Artifact
    #  uses: actions/upload-artifact@master	
    #  with:	
    #    name: mta
    #   path: ./mta_archives/cap-github-actions_1.0.0.mtar
